---
development:
  cloud_name: fuchs-agil
  api_key: '164211298462787'
  api_secret: CkAGP3OCkrpSFTYFuTSjemavUro
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: fuchs-agil
  api_key: '164211298462787'
  api_secret: CkAGP3OCkrpSFTYFuTSjemavUro
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: fuchs-agil
  api_key: '164211298462787'
  api_secret: CkAGP3OCkrpSFTYFuTSjemavUro
  enhance_image_tag: true
  static_file_support: false
